### ISSUE TITLE
non-200 status code do not generate an error anymore

### ISSUE THREAD

**Issue by clementnuss** [postfinance/kubenurse#138]
when an http request produces a status code different than `200`, an error is produced:
https://github.com/postfinance/kubenurse/blob/e139b8c94ab4940f5af31c5437275991ef19350d/internal/servicecheck/transport.go#L52

however, with the changes I introduced in https://github.com/postfinance/kubenurse/pull/125, this status error is now silently discarded.

IMO, we should at least log this error, and we could also consider this as an error and increase the error counter.

@zbindenren what's your take on this. ?

**Comment by zbindenren** [comment]
I think we should increase error counter and log it.
