### ISSUE TITLE
Question: How to contribute?

### ISSUE THREAD

**Issue by bramvandenklinkenberg** [postfinance/kubenurse#22]
Hi, I was thinking that I maybe can contribute by making a helm repo for kubenurse.
I was wondering if this was maybe already something planned by the maintainers.. Or maybe not wanted.

Any comments/guidelines on how to contribute?

Grz Bram

**Comment by bramvdklinkenberg** [comment]
nvm... rtfm

**Comment by djboris9** [comment]
Hi Bram,

I no longer work at PostFinance but they are also using Helm, so I guess your PR will be welcome.

@zbindenren Ping, Ping, Ping. Can you help Bram?

**Comment by bramvdklinkenberg** [comment]
Just found the contributing guidelines...need new glasses ;-).
If creating a helm chart and repo is desired then I will create the PR for it.

**Comment by bramvdklinkenberg** [comment]
[PR](https://github.com/postfinance/kubenurse/pull/23) created

**Comment by bramvdklinkenberg** [comment]
[PR](https://github.com/postfinance/kubenurse/pull/24) created

**Comment by zbindenren** [comment]
Thank you for your contribution. I am currently on vacation and look into it when I am back.
