### ISSUE TITLE
"Moved Permanently" response from /alive endpoint.

### ISSUE THREAD

**Issue by eli-halych** [postfinance/kubenurse#26]
I install kubenurse as a Helm chart by placing [these files](https://github.com/postfinance/kubenurse/tree/master/examples) to the chart's "templates" folder. Next, I install it with `helm install .`. Then from a pod, where I `kubectl exec` into, I try to send an HTTP request to `http://kubenurse.kube-system.svc.cluster.local:8080` with `curl` and get this response:
```bash
<a href="/alive">Moved Permanently</a>.
```

**Comment by djboris9** [comment]
Hi @eli-halych 

This works as designed. When you do a `curl -L` you will be redirected to the `/alive` endpoint and will see the expected state. Or you can directly access `http://kubenurse.kube-system.svc.cluster.local:8080/alive`

If you wish to access the metrics, you can navigate to `http://kubenurse.kube-system.svc.cluster.local:8080/metrics`.
More information are available [here](https://github.com/postfinance/kubenurse#http-endpoints)
