### ISSUE TITLE
Request: Create a gh-pages branch 

### ISSUE THREAD

**Issue by bramvdklinkenberg** [postfinance/kubenurse#27]
Hi @zbindenren , could you create a gh-pages branch in the repository so I can create a PR for the helm repo? It requires a gh-pages branch, but that is not something I can create through my forked repo (I believe).

Grz Bram

**Comment by zbindenren** [comment]
Hi @bramvdklinkenberg it should work now: https://postfinance.github.io/kubenurse/

**Comment by bramvdklinkenberg** [comment]
yes, thanks @zbindenren !
