### ISSUE TITLE
configurable k8s service name

### ISSUE THREAD

**Issue by ghouscht** [postfinance/kubenurse#3]
https://github.com/postfinance/kubenurse/blob/master/pkg/checker/checker.go#L64 --> at least the suffix ".cluster.local" should be configurable?

**Comment by djboris9** [comment]
`cluster.local` can be configured with the `--cluster-domain` kubelet flag. If we remove `cluster.local` from checker.go, it will increase the number of DNS requests (search domains). Perhaps we could set `https://kubernetes.default.svc:%s/version` as default and allow to override this setting by an environment variable?

**Comment by ghouscht** [comment]
sounds good!

**Comment by djboris9** [comment]
Issue will be closed due to age. Please reopen if anyone needs it.
