### ISSUE TITLE
404 Not Found service endpoints

### ISSUE THREAD

**Issue by eli-halych** [postfinance/kubenurse#33]
```json
"user_agent": "curl/7.76.1",
 "request_uri": "/alive",
 "remote_addr": "127.0.0.1:38864",
 "api_server_direct": "ok",
 "api_server_dns": "ok",
 "me_ingress": "404 Not Found",
 "me_service": "Get \"http://kubenurse.kube-system.svc.cluster.local:8080/alwayshappy\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)",
 "neighbourhood_state": "ok",
```

Any idea why /alive and other endpoints return 404 when trying to send requests to the service?

**Comment by djboris9** [comment]
Do you have any NetworkPolicies or similar in place, which are causing the timeout? Are other services reachable as usual (=kube-proxy works)?

**Comment by eli-halych** [comment]
Is there any documentation or an example how to enable traefik ingress routing for kubenurse? The idea is to use `mydummyurl.com/kubenurse` path within the Kubernetes cluster.

**Comment by eli-halych** [comment]
Alright, I noticed it is actually working when I check the `/metrics` endpoint. And all the pods are "turning on/off" meaning readiness probes are succeeding, then failing and then it's on repeat.

**Comment by djboris9** [comment]
Could you please share your Helm values you are using to deploy the kubenurse? So I can deploy it with the same configuration and have a better understanding what is failing.

**Comment by eli-halych** [comment]
I solved it with this MR #38 - a new chart designed for Traefik version 2.x that allows access to Kubenurse via a path example.com/kubenurse/* .

This was my case. And since I used Traefik 2.x, I switched Ingress resource and backend/frontend logic to the one suitable for version 2.x - Middlewares and IngressRoutes. Works like a charm!

**Comment by eli-halych** [comment]
@djboris9, what do you think about this MR #38?

**Comment by clementnuss** [comment]
@eli-halych cf my comment in #38. 

closing this issue, as it has more to do with Traefik Ingress Controller peculiarities than with an actual issue.
