### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by liyongxian** [postfinance/kubenurse#35]
Doc has no  Json of Grafana Dashboard For kubenurse

**Comment by eli-halych** [comment]
I was also looking for it and couldn't find it in the repo.

**Comment by eli-halych** [comment]
@djboris9 can you help us with that, please?

**Comment by djboris9** [comment]
Sorry @liyongxian and @eli-halych I'm currently busy and had missed the issues.

Could you try out this dashboard: https://github.com/djboris9/kubenurse/blob/d6b2d260ce150d69c5e39240dd3d4ea3e0e61232/doc/grafana-kubenurse.json

If it works, I will merge it into this repository and probably add it to helm too.

**Comment by ywllongge** [comment]
Thanks@[djboris9]

**Comment by djboris9** [comment]
Hi @eli-halych 

Thanks for the feedback! I just merged the dashboard into the master branch with #40 .

I will open a new issue to incorporate and test the `ServiceMonitor` into the helm chart as you've written and close this issue.

Is this ok for you?

**Comment by djboris9** [comment]
PR #42 implements the `ServiceMonitor`. Therefore I will close this issue. Feel free to provide feedback or reopen it.
