### ISSUE TITLE
Proposal: Use httptrace to get advanced metrics and error messages

### ISSUE THREAD

**Issue by djboris9** [postfinance/kubenurse#45]
# Proposal
We should use [httptrace](https://pkg.go.dev/net/http/httptrace) for requests done by the kubenurse in order to get more advanced error details like DNS failures and statistics like time-to-first-byte.

## Positive impact
We will log a little bit more on http errors and get new metrics from the requests. This allows users for easier debugging like #44, where only a http client error message is present and will get insights on different latencies.

## Negative impact
There could be a small increase in log messages and metrics.

## Notes
There is already httptrace included using prometheus framework but it needs to be extended.

**Comment by clementnuss** [comment]
working on that feature in https://github.com/postfinance/kubenurse/tree/cjmn-patch-0314
will soon be ready :)
