### ISSUE TITLE
Kubenurse shold not try to bind pvc on startup

### ISSUE THREAD

**Issue by zbindenren** [postfinance/kubenurse#9]
When kubenurse does that, it stays in pending state and all other tests fail. It would be better to do that periodically.

**Comment by djboris9** [comment]
This is due to our internal configuration as we attached volume(es) to the Pod in order to check storage access.

But as soon as we implement https://github.com/postfinance/kubenurse/issues/8 we can move the volume mount to the child/patient. It would enable us to detect storage access loss too.

**Comment by zbindenren** [comment]
Ok, closing.
